on:
  push:
    branches:
      - live

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '17'
      - run: cd frontend/
      - run: rm -rf package-lock.json
      - run: npm install
      - run: npm run build
      - name: Deploy to production
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PRODUCTION_HOST }}
          username: ${{ secrets.PRODUCTION_USERNAME }}
          password: ${{ secrets.PRODUCTION_PASSWORD }}
          key: ${{secrets.PRODUCTION_KEY}}
          script: |
            cd /home/leventvadmin/leventv
            git pull origin live
            npm install && npm run build
            pm2 reload all
