on:
  push:
    branches:
      - live

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: live
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - run: npm install
      - run: npm install --prefix frontend
      - run: npm run build
      - name: Deploy CLIENT to production
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.PRODUCTION_HOST }}
          username: ${{ secrets.PRODUCTION_USERNAME }}
          password: ${{ secrets.PRODUCTION_PASSWORD }}
          key: ${{secrets.PRODUCTION_KEY}}
          source: "frontend/build"
          target: "/home/leventvadmin/leventv"
      - name: Deploy API to production
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PRODUCTION_HOST }}
          username: ${{ secrets.PRODUCTION_USERNAME }}
          password: ${{ secrets.PRODUCTION_PASSWORD }}
          key: ${{secrets.PRODUCTION_KEY}}
          script: |
            cd /home/leventvadmin/leventv
            git pull origin live
            pm2 reload all
